### ISSUE TITLE
Create a reference XML article(s) that contains all the potential tags/attributes that are required in the 'back' section to support an Insight Article

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#192]
## Description
As a Developer, I need a reference insights article so that I can use it for testing whilst developing.

## DoD
- [ ] A DAR archive, that contains a reference XML article with all the potential tags/attributes that might be found in the 'back' section of an insights article, committed into a repository in Github.

**Comment by fred-atherden** [comment]
@joelsummerfield, which GitHub repo should this be deposited to? Or should I create one?

**Comment by NuclearRedeye** [comment]
@FAtherden-eLife Good Question, I think for now that it might be an idea to create one, maybe something like 'reference-manuscripts' or similar, and just commit it there. Justification being that I can imagine that there will be more than one package that will want to make use of it.

**Comment by fred-atherden** [comment]
Thanks @joelsummerfield , done. Committed an Insight kitchen sink here https://github.com/libero/reference-manuscripts/blob/master/insight-kitchen-sink/elife-00001.xml

@JGilbert-eLife, @Melissa37 - please can you take a look and let me know if there's anything I've missed? (bear in mind that I'm just doing `back` stuff atm and will add more at a later point)

**Comment by Melissa37** [comment]
Hi @FAtherden-eLife 

I know this is a comment not on the back, but think it should be changed now :-)

The id and rid should be to "con" not "conf" cor conflict.
This matches with the JATS4R recommendation.
I think it might still be there in your tagging because we had to use conf because con was used for contributions....but contributions will follow the other JATS4R recommendation for credit taxonomy so we're OK using con now.
Thanks!

**Comment by fred-atherden** [comment]
Sure, done.

**Comment by JGilbert-eLife** [comment]
I don't think we normally list eLocation IDs for bioRxiv references, since they have DOIs. We do list them on arXiv references though . . .

This covers most variations on journal references but I think we should include ones that don't have volume or page range as well. Plus web references without a parent site e.g

```
    <ref id="bib50">
        <element-citation publication-type="web">
            <person-group person-group-type="author">
                <name>
                    <surname>Walker</surname>
                    <given-names>J</given-names>
                </name>
            </person-group>
            <year iso-8601-date="1994">1994</year>
            <article-title>Solar System Live</article-title>
            <ext-link ext-link-type="uri" xlink:href='https://www.fourmilab.ch/solar/'>https://www.fourmilab.ch/solar/</ext-link>
            <date-in-citation iso-8601-date="1995-09-10">September 10, 1995</date-in-citation>
        </element-citation>
    </ref>

```

**Comment by fred-atherden** [comment]
@JGilbert-eLife, can't see a single instance of an arXiv `elocation-id` in the archive (or bioRxiv, as you say). Is it a case of house style that we don't include `elocation-id`s for bioRxiv refs? It seems `elocation-id` is not allowed for preprint refs in the reference schematron (why is that?), but I don't see why we shouldn't do so if there's one present...

I'll commit an edited file with that journal/web addition after we clarify the above.
