### ISSUE TITLE
Review sample XML file from Exeter that includes processing instructions

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#229]
Exeter have supplied us with a sample XML file that includes some example processing instructions. This needs to be reviewed and understood so that we can understand what the specific tags/elements/attributes are and understand how they will fit with our XML standards.

# DoD:
- [ ] Document that captures the changes required.
- [x] Confirmation one way or the other regarding if the processing tags can be made publicly available or not.
- [ ] If the above is OK, then reference article including processing tags added to the reference-manuscripts repository.

**Comment by Melissa37** [comment]
To Exeter: Just to clarify - if the examples and instructions are on our website they get published under an MIT license so they can be re-used by anyone.

From Exeter:
I understand that the instructions can be reused by anyone. That's perfectly fine with us.

**Comment by fred-atherden** [comment]
Attaching file here for reference [elife-46924_processing_instruction_sample.xml.zip](https://app.zenhub.com/files/195217312/9e82552b-70ac-475f-adac-94376a29cbaa/download).

Instruction documentation is [here](https://docs.google.com/document/d/1H7Tbyz7Y3KrinaxtS66WoJ6XSzJ4neqIVFVvSi_0V2c/edit?ts=5dbaec2f).

**Comment by fred-atherden** [comment]
@joelsummerfield 
> Document that captures the changes required.

Does this mean a document which outlines new requirements or a document which outlines what technical changes are required in Libero Editor? (For example, presumably there's something in the internal Schema about processing-instructions??)

> If the above is OK, then reference article including processing tags added to the reference-manuscripts repository.

Are you happy for me to add these processing instructions to an already pre-existing kitchen sink (for example the 'body' one) rather than the file Exeter have provided? Their file will contain content that we don't need to support for MVP.

**Comment by fred-atherden** [comment]
PR added https://github.com/libero/reference-manuscripts/pull/4.
