### ISSUE TITLE
Interface/system configuration based on Schematron setup

### ISSUE THREAD

**Issue by NickDuf** [libero/editor#263]
#### Who is suggesting this feature?
Joel Summerfield and Nick Duffield

#### Please describe the problem this feature is intended to solve
Potential adopters of the Libero Editor have a variety of XML requirements that need to be supported. However, not all of these requirements are shared by others and so there is a need for an individual adopter to be able to configure the tool to match their needs.

#### Please provide the context in which the proposed feature will be used
A production team interested in adopting Libero Editor for article proofing and will need to capture XML specific to their organization's requirement.

#### Who does the problem affect?
Production Staff

#### What is the expected value this feature will add to the project?
Making Libero Editor easily configurable to an organisation’s unique needs will make the tool easier to adopt

#### Please provide links to evidence you have to support this request (optional)
No supporting information at present

#### Ideas on how we may solve this problem (optional)
Make use of an organization's existing validation tools, e.g. xquery, to generate a configuration file for the Editor which can be used to tailor its behaviour with regards to the structure of the XML, and the elements and attributes displayed to the user in  the Editor’s interface.

**Comment by NickDuf** [comment]
Further Info from Joel

I was thinking about how vendors could go about configuring the Editor, and I had a thought about having the editor generate a configuration from a 'schematron' file.
So, I'll try and explain this a bit better. The issue with the Editor at the moment is that to alter it's behaviour you need to change the code, even if it's something as simple as just adding support for an extra attribute or similar. In the real world, this isn't going to really be applicable for people and what we don't really want is a vast amount of divergence between users of the editor.

The best approach in my mind is to build the Editor to conform to the JATS (or JATS4R) standard, and that would be it's default behaviour. It will allow you to load XML, validate against the JATS spec highlighting issues and errors, and then write out XML that conforms to JATS.

From the user stories, the differences between each organisation are the specific attributes/elements that they use and where elements are located in the tree, and hence this is what needs to be configurable. As an example, eLife want 'aff' elements to appear under the 'contrib-group' element, whereas others want them under the 'article-meta' element. Both are valid per the spec, but we need to ensure that when a user saves a manuscript the xml written out conforms to their preferred style. It also impacts validation indicators in the UI, where rules need to dictate what should be displayed and what shouldn't.

At eLife, we have a schematron file that we use to validate the structure of our XML, and it makes me think that other organisations might have similar tools as well. What we should aim to do is have a utility that can take a 'schematron' or similar file, and generate a config file for the editor based on that.

That in theory I think could complete around 90-95% or all the configuration the tool would need, and really lower the barrier of entry for people making use of the tool by not requiring a developer to complete the customisation.

This won't be suitable for all, but I think we should start exploring this as an option and find out more about how other organisations validate their XML and what tools they use and have.

**Comment by fred-atherden** [comment]
Just had a thought which I'll add here before I forget.

Schematron files generate a separate report (an XML file in SVRL). They are compiled by an XSLT into a (separate) XSLT file, which is then run on the XML (article) file in order to produce a report.
**Steps**:
1. Schematron + Compiler XSLT = Validation XSLT
2. Validation XSLT + Article XML = Report XML
3. Editor compares Report XML with Article XML in order to display validation info
4. Editor displays article with accompanying validation messages

However, we could use [SchXslt](https://github.com/schxslt/schxslt), to instead compile an XSLT which, when run against the article file, would produce an _article_ XML file exactly as it was, but with additional attributes included that indicate whether a certain element has fired a message.
**Potential new steps**:
1. Schematron + SchXslt Compiler XSLT = SchXslt Validation XSLT
2. SchXslt Validation XSLT + Article XML = Revised Article XML
3. Editor displays article with accompanying validation messages

Doing this would skip a step. Could be used in a production workflow (for a custom Schematron), and for the purposes of feeding back what elements are allowed/supported in Editor in general.

**Comment by NickDuf** [comment]
@FAtherden-eLife is this something we should run past the SIG as a potential option for configuration?

**Comment by fred-atherden** [comment]
@NickDuf, It's just about how best to implement the Schematron. I don't think it's something we would want/need to run past the SIG.

**Comment by NuclearRedeye** [comment]
@NickDuf It would be interesting to discuss with the SIG what tools they currently have/use (if any) to validate XML, be interesting to know whats popular and what's not.

**Comment by NickDuf** [comment]
@NuclearRedeye sounds good! I'm particularly keen to speak to Erudit as I know they publish for different journals. I'll draft some questions and get everyone's input.
