### ISSUE TITLE
Display and Edit Article citation details

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#364]
This issue covers the implementation of support for the `<volume>` and `
<elocation-id>` elements.

# User Stories

https://github.com/libero/editor/issues/21

# Design
https://invis.io/A8WXRN9PQBF#/419110165_article-Info-2

# DoD
- [x] Editor updated so that the user can see and edit all the required fields.
- [x] Solution **reviewed** and **approved** by the designer.
- [x] Solution **reviewed** and **approved** by required stakeholders.
- [x] New version of the Editor, deployed to the staging environment and publicly accessible.

**Comment by NuclearRedeye** [comment]
Estimate:
Design: 0.25d
Dev: 1d

**Comment by fred-atherden** [comment]
Volume and eLocation ID displays twice in the article information display. e.g. from [54296](https://libero-editor--staging--test-cluster.elifesciences.org/?articleId=54296):
![Screenshot 2020-08-12 at 09.15.41.png](https://images.zenhubusercontent.com/5d5a77bfe56ed603cbb191f6/5750ec08-44ff-40f8-8c5c-dd3c591843ce)

**Comment by fred-atherden** [comment]
In [00001](https://libero-editor--staging--test-cluster.elifesciences.org/?articleId=00001) the volume is 337:
![Screenshot 2020-08-12 at 09.18.35.png](https://images.zenhubusercontent.com/5d5a77bfe56ed603cbb191f6/8e0bc42c-d2ed-4fd4-a9de-a3cf1f7d9bd6)

This is incorrect. This article XML doesn't have a volume. Presume that this being taken from the first volume element in the article, which in this case happens to be [the volume number for the first reference](https://github.com/libero/editor-reference-manuscripts/blob/faa1db3aae98636b9a59a262c88e345f26d4954a/manuscripts/00001/manuscript.xml#L106).

So instead of pulling this information from the first volume element in an article, it should always be pulled from the volume in the `article-meta` element. If there isn't one, then nothing should display.

**Comment by fred-atherden** [comment]
The same thing described with volume above is occurring with the eLocationID. 00001 has no eLocation ID, so nothing should display (instead of e42679). 

The information should be pulled from the `<elocation-id>` element in the `<article-meta>` element.

**Comment by fred-atherden** [comment]
Looks good now, thanks
