### ISSUE TITLE
Competing interest selection should have option for 'select competing interest'

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#484]
Create a new author, in the modal the 'Competing Interest' control should have updated with a message. At the moment it is just blank.

# DoD
- [x] Control updated to display the text 'Select competing interest' when no competing interest has yet been declared.
- [x] Change wording of first option from 'Select competing interest' to 'Please choose'.
- [x] First item in the list should be styled differently. But only if the first item in the list is some placeholder text like 'Select item'.

**Comment by fred-atherden** [comment]
I think there may have been a misunderstanding, possibly because of some unfortunate unintended ambiguous wording above:
> when no competing interest has yet been declared.

My understanding was that 'Select Competing Interest' should only display if _neither_ option ('Has competing interest' or 'No Competing interest') has been selected.

So, for authors which have 'No competing interest' selected, what should display is 'No competing interest', rather than 'Select Competing Interest'


**Steps to reproduce**
Visit https://libero-editor--staging--test-cluster.elifesciences.org/?articleId=54296, and open up the modal for Felicity Emerson.
Since she is already 'No competing interests declared', I'm expecting to see 'No competing interest', but I actually see:
![Screenshot 2020-07-16 at 10.11.29.png](https://images.zenhubusercontent.com/5d5a77bfe56ed603cbb191f6/c9383143-6f68-455c-947d-41d91e877a53)

If I change this to 'Has competing interests', save, then re-open the modal, then 'Has competing interests' displays. This is good and expected behaviour. The same should be the case for 'No competing interest'.

**Comment by fred-atherden** [comment]
Also I think maybe we should discuss whether 'Select Competing Interest' should be an option which can be picked.

I think for eLife purposes, it should it just be the default text which displays when neither of the other two options has been picked.

![Screenshot 2020-07-16 at 10.17.44.png](https://images.zenhubusercontent.com/5d5a77bfe56ed603cbb191f6/371b18bd-c38f-4d5a-aeb0-aaaadf9148c9) 

However, I can see a use-case for the SIG, whereby they don't want to have to select either option (because perhaps they don't declare competing interests - or they do so in a different way perhaps), and so leaving it as 'Select competing interest' might be desired.

**Comment by NickDuf** [comment]
@ilya-zhuravel here is a [design](https://invis.io/A8WXRN9PQBF#/414680495_author-Info-2) to help with the remaining todo items

- Option text change
- Option style to placeholder grey (leave if this cannot be done easily)
