### ISSUE TITLE
Create a modal to edit a related article

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#488]
# Design
https://projects.invisionapp.com/d/main#/console/19776007/419110166/preview

# DoD
- [ ] Can edit a related article from a modal as per the design.
- [ ] Reviewed and approved by designer.
- [ ] Reviewed and approved by stakeholders.

**Comment by fred-atherden** [comment]
Thanks @ilya-zhuravel, In the modal, I think we need the Article type options to be the `related-article-type` value, rather than a human readable version of it. i.e.:
- "article-reference" instead of "Article reference", 
- "commentary" instead of "Commentary", 
- "commentary-article" instead of "Commentary article" 
and so on.

![Screenshot 2020-07-23 at 09.54.19.png](https://images.zenhubusercontent.com/5d5a77bfe56ed603cbb191f6/c33788d4-8e4e-4ace-969f-3f67ac92725a)

Looks fine outside of the modal though, where the attribute value is displaying:
![Screenshot 2020-07-23 at 09.55.19.png](https://images.zenhubusercontent.com/5d5a77bfe56ed603cbb191f6/808a836f-d4c0-4d6d-a349-04a3b3d9dd09)

**Comment by NickDuf** [comment]
@ilya-zhuravel all looks good to me. Some minor tidy up for the text-fields as they are falling short of the card on the right-hand side [see img for ref](https://images.zenhubusercontent.com/5d5a52c42298e3000103df57/ecc322de-7743-4e86-a7b4-05b14eed7da6)

**Comment by fred-atherden** [comment]
Looks good for production now that the article-type values have been updated.

**Comment by NickDuf** [comment]
@ilya-zhuravel just needs equal space either side of cards.

**Comment by NuclearRedeye** [comment]
Closing as raised a new issue to cover the design concern above.
