### ISSUE TITLE
Support for Paste with formatting 

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#533]
# DoD
- [x] When pasting text, by default the formatting should be preserved.
- [x] When pasting test, I should be able to paste without formatting using 'CTRL/CMD+SHIFT+V'.

**Comment by fred-atherden** [comment]
Everything except italic is working for me. It would be good if we could also have italics copied since this is a very common form of emphasis in scientific content.

Top line is original, bottom line is copied.
![Screenshot 2020-09-14 at 10.13.44.png](https://images.zenhubusercontent.com/5d5a77bfe56ed603cbb191f6/156fa5d4-4666-41ae-b639-22df62d3d585)

**Comment by fred-atherden** [comment]
It would also be nice if, when you paste without formatting, the citation is retained as plain text. Although, this isn't as big of a deal, and if it takes a lot of work to fix, then it's acceptable for MVP.

![Screenshot 2020-09-14 at 10.16.44.png](https://images.zenhubusercontent.com/5d5a77bfe56ed603cbb191f6/67b43b1d-f28d-4711-93bb-3317243a7633)

**Comment by ilya-zhuravel** [comment]
@FAtherden-eLife the feedbach has been addressed

**Comment by fred-atherden** [comment]
Thanks @ilya-zhuravel, looks good to me. Think we're good to close, unless @NickDuf has anything to add?

**Comment by NickDuf** [comment]
@FAtherden-eLife @ilya-zhuravel are we talking about pasting within the app or from something like word to the app?
