### ISSUE TITLE
Support for inserting a new section/heading from the toolbar

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#534]
# DoD
- [ ] From the menu, I should be able to select a heading and that should convert the current paragraph to a heading.
- [ ] The above holds true even when i've selected just a sub portion of a paragraph.
- [ ] Can change the heading from any type to another.
- [ ] Undo/Redo should work.

**Comment by fred-atherden** [comment]
Looks good. One question though, perhaps for @NickDuf.

The toolbar says 'Paragraph' all the time. Should the display there be contextual? i.e. if the cursor is in a Heading 1, should it say Heading 1 instead of Paragraph?
![Screenshot 2020-09-15 at 09.10.21.png](https://images.zenhubusercontent.com/5d5a77bfe56ed603cbb191f6/d1e06093-66b7-4217-81d1-4c5e1bcd31a5)

**Comment by NickDuf** [comment]
@FAtherden-eLife Good spot. Yes I think the toolbar should change to reflect the current style. @ilya-zhuravel I seem to recall we agreed not to bother with 'The above holds true even when i've selected just a sub portion of a paragraph' so all clear from me as long Fred's point is addressed.

**Comment by NuclearRedeye** [comment]
Raised #543 to cover the above item, hence closing this.
