### ISSUE TITLE
Investigate solutions for collaborative editing / tracking changes when working with a prosemirror client

### ISSUE THREAD

**Issue by Cooryd** [libero/editor#591]
While we don't need to implement these features right now we do need to decide how we will be storing changes and looking into these may prevent headaches in future.

**Comment by norisalsaadie** [comment]
Update 1: 

The following was looked into:
- ShareJS / ShareDb due to their take on OT and support for mongo with a full backend solution. It wasn't clear if this would conflict with ProseMirror's approach as outlined by the author here (https://github.com/ProseMirror/prosemirror/issues/6) and a decision was taken to abandon this track for now
- Prose Mirror Collab - https://github.com/ProseMirror/website/tree/9b330f9a3f86e2ed296665ad7d129639c4ebf276/src/collab
- Additions: https://discuss.prosemirror.net/t/guide-docs-for-writing-server-code-that-enables-collaborative-editing/64/5 and https://github.com/fiduswriter/fiduswriter
- Track changes example https://prosemirror.net/examples/track/#:~:text=Tracking%20changes,to%20see%20what%20they%20did.

**Comment by norisalsaadie** [comment]
After the spike, the decision was to start with a simpler solution similar to the track changes tickets, . Overview of the current approach:

- Client would send a list of changes / transactions that would be stored in Mongo
- While the transactions / changes are still pending, they won't be applied to the main content
- If a transaction is applied / accepted then this is transformed on the backend and the xml is updated with a version bump 
- Depending on the number of concurrent editors and and number of edits, some work will be required on Guarantee in-order message delivery of changes / transactions. An implementation can be found in https://github.com/josephg/ShareJS

Broken down into:

- https://github.com/libero/editor/issues/593
- https://github.com/libero/editor/issues/594
- https://github.com/libero/editor/issues/595
- https://github.com/libero/editor/issues/596
