### ISSUE TITLE
Update editor to support new figure upload workflow

### ISSUE THREAD

**Issue by NuclearRedeye** [libero/editor#643]
TODO

# DoD
- [ ] User can upload a TIFF format image and sent it to the server.
- [ ] Whilst uploading, a placeholder image is displayed to the user.
- [ ] Once the server has converted the image to an Editor friendly format, e.g. JPG. The client updates to display that figure.
- [ ] Solution deployed to staging.
- [ ] Solution reviewed and approved by stakeholders.
- [ ] Solution deployed to production.

**Comment by fred-atherden** [comment]
Unsure if this is ready for my review yet, but currently I see that tif files are still greyed out and un-clickable for the user when trying to replace:
![Screenshot 2021-02-08 at 13.29.31.png](https://images.zenhubusercontent.com/5d5a77bfe56ed603cbb191f6/c8ca7800-6204-403d-b4e4-51e894e534e5)

**Comment by ilya-zhuravel** [comment]
@NickDuf @Cooryd @NuclearRedeye I was looking into implementing user feedback (loading spinner) for figure update. I can't think of a way to show an image upload inside a figure. To show spinner image we would need change the node (and the document) to show the loading placeholder, then initiate a new image upload and when server responds with the new uploaded asset url we update the node again. The thing is in-between the two events while the image is being uploaded user can make a lot of changes, including deleting a figure or even reverting his previous action. Handling error response adds more problems to this because we would have to manually fix the changes history. Is there a change we could delay this implementation? or maybe just slap a loading shade over the entire application screen to prevent user from doing anything?

Do we need to implement the placeholder image for figures for MVP? I would delay this until we figure out and implemented tracked changes.

**Comment by NuclearRedeye** [comment]
Discussed, this is complex and would be better reviewed after tracked changes, hence dropping to later in the backlog.
