### ISSUE TITLE
Configure xslt service to expose v1 and v2 endpoints

### ISSUE THREAD

**Issue by Cooryd** [libero/editor#770]
Using a `.xqm` file we should configure 2 rest endpoints for converting passed xml into v1 or v2 xml.

v1 -> v2
https://app.zenhub.com/files/195217312/30bff985-f5eb-402f-b1d3-5a7657d4c06e/download

v2 -> v1
https://app.zenhub.com/files/195217312/a1e34e9a-061b-494c-a3cc-544742d4d1c6/download

Very basic xqm snippet which could do the job: 

Probably worth asking @FAtherden-eLife to review this as I have very little experience with XQuery.

```
module namespace local = 'some.local.namespace';

declare %rest:path("/convert/v2") %rest:POST("{$xml}") %input:text("xml","encoding=UTF-8") function local:v1tov2($xml) {
  let $style := doc('./v1-v2.xsl')
  return xslt:transform($xml, $style)
};
declare %rest:path("/convert/v1") %rest:POST("{$xml}") %input:text("xml","encoding=UTF-8") function local:v2tov1($xml) {
  let $style := doc('./v2-v1.xsl')
  return xslt:transform($xml, $style)
};
```

Remember to update `README.md` to explain how to test these endpoints. Can base of of https://github.com/elifesciences/basex-validator-docker/blob/master/README.md.

**Comment by fred-atherden** [comment]
Yup. Alternatively you could supply the version as a second parameter if that's easier. Something like this:
```
module namespace e = 'http://elifesciences.org/modules/transform';
import module namespace rest = "http://exquery.org/ns/restxq";

declare
  %rest:path("/transform")
  %rest:POST("{$data}")
  %output:method("json")
function e:transform($data as item()+)
{
  if ($data[. instance of document-node()] and $data[. instance of xs:string]) then (
    let $xml := $data[. instance of document-node()]
    let $version := $data[. instance of xs:string]
    return
    if ($version="1") then
      let $xsl := doc('./v2-to-v1.xsl') 
      return xslt:transform($xml,$xsl,map{"indent":"no"})
    else if ($version="2") then
      let $xsl := doc('./v1-to-v2.xsl') 
      return xslt:transform($xml,$xsl,map{"indent":"no"}) 
    else error(xs:QName("basex:error"),'The version number must be 1 or 2')
  )
  else (
    error(xs:QName("basex:error"),'An xml document and version number (1 or 2) must supplied')
  )
};
```
should work using `curl  -F xml=@file.xml -F "version=2"  http://localhost:8984/transform` for example.

Presumably you want the output as json (as in your example above)?

Also baseX will strip the preamble (processing instruction(s) and dtd) at the top of the XML file by default. As I recall, the settings can be changed so that it doesn't get stripped, but I think that means each file would have to be valid against its DTD, which we don't want in this case. I'll look into it further, because I think ideally we would include them (they will be different in the differing versions).

**Comment by fred-atherden** [comment]
Looks like if we want to include the xml/doctype declaration, then the response has to be in xml format and set in 
`%output` options. Using your example above this could be done like so:
```
module namespace e = 'some.namespace';
import module namespace rest = "http://exquery.org/ns/restxq";

declare
  %rest:path("/convert/v2")
  %rest:POST("{$xml}")
  %output:method("xml")
  %output:indent("no")
  %output:omit-xml-declaration("no")
  %output:doctype-public("-//NLM//DTD JATS (Z39.96) Journal Archiving and Interchange DTD with MathML3 v1.2 20190208//EN")
  %output:doctype-system("JATS-archivearticle1-mathml3.dtd")
function e:transform($xml as document-node())
{
  let $xsl := doc('./xsl/v1-to-v2.xsl') 
  return xslt:transform($xml,$xsl,map{'indent':'no'})
};
```

[Edit: since these are different across the two versions, then it would have to be two separate endpoints, rather than one with an extra parameter]
