### ISSUE TITLE
Check that article type and MSA is pulled correctly 

### ISSUE THREAD

**Issue by Cooryd** [libero/editor#774]
Article type:
v1
```
<subj-group subj-group-type="display-channel">
  <subject>Insight</subject>
</subj-group>
```

v2
```
<subj-group subj-group-type="heading">
  <subject>Insight</subject>
</subj-group>
```

Two MSAs:
v1
```
<subj-group subj-group-type="heading">
                    <subject>Evolutionary Biology</subject>
                </subj-group>
                <subj-group subj-group-type="heading">
                    <subject>MSA</subject>
                </subj-group>
```
v2
```
<subj-group subj-group-type="major-subject">
                    <subject>Evolutionary Biology</subject>
                    <subject>MSA</subject>
                </subj-group>
```

**Comment by ilya-zhuravel** [comment]
We are currently not parsing these subject group types for MVP. 
Only parsing `subject`. This change should not affect Editor.

**Comment by ilya-zhuravel** [comment]
@FAtherden-eLife Could you confirm, we shouldn't parse these subjects for MVP?

**Comment by fred-atherden** [comment]
@ilya-zhuravel, they should be parsed for MVP.

Subjects in the `<subj-group subj-group-type="major-subject">` should appear after 'Subject(s)' (red box).
The subject under `<subj-group subj-group-type="heading">` should appear after 'Article type' Blue box.
<img width="610" alt="Screenshot 2021-04-14 at 20 51 40" src="https://user-images.githubusercontent.com/43879983/114770763-b3df2180-9d63-11eb-8e28-da8401c65445.png">

Note that in the screenshot above it's displaying incorrectly, because this will be using the v1 XML. As far as I understand, Editor is already configured to accept the v2 tagging, so I don't think any change is needed here.
