### ISSUE TITLE
Investigate options for ISO country code input

### ISSUE THREAD

**Issue by Cooryd** [libero/editor#797]
See https://app.zenhub.com/workspaces/libero-editor-5d56a6cfaa13c900012ad75b/issues/libero/editor/719 

#DoD

- [ ] approved design for the ISO input

**Comment by NickDuf** [comment]
@FAtherden-eLife would you mind checking the below information for me?

Design proposal is [here](https://invis.io/A8WXRN9PQBF#/418480046_author-Affiliation-3)

##### User stories
   -  As an author, I want to be able to set a country for my affiliation so that I can provide accurate information about my place of work
   - As a Production Editor I need to be sure that an authors affiliation information is complete, so that I can meet specified journal standards

##### Constraints
- We need a politically neutral set of options for users to choose a country from
- Making an incorrect choice should not be possible. i.e. by selecting a country the correct ISO will be assigned if there is one
- Staff can trust the system resulting in one less check. Libero Editor is designed to promote less need for manual checks making proofing more accurate and efficient 

## Initial suggestions
##### We add another input to the affiliation modal for selecting the correct ISO_3166-1 2 letter country code
   - Authors and staff can't be expected to know which country code to pick out of the many choices 
   - Asking for an ISO country choice places a burden on authors and staff to be sure the correct information has been entered
   - A wrong choice can be made which presents the issue of user input error

##### We do a look up with what we have and if we find a match assign and if not just go without
   - If a country is misspelled look up may fail
   - Additional proofing is required by production to ensure that look up has worked

**Comment by Melissa37** [comment]
@FAtherden-eLife I think the introduction of ROR amends this requirement a bit now?

**Comment by fred-atherden** [comment]
> @FAtherden-eLife I think the introduction of ROR amends this requirement a bit now?

Thanks @Melissa37, yes and no. This is just about changing the country field from text input to a dropdown list (so that we can put the ISO code in the XML). We'll still need this for institutions without ROR ids. Obviously if there's a ROR, the country would be known, so we can set the country/ISO code automatically, but I think we can deal with that when we're looking at adding ROR in.

Thanks for the reminder about ROR!
